apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodemongo.fullname" . }}
  labels:
    {{- include "nodemongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.exposePort }}
      targetPort: {{ .Values.service.NodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "nodemongo.selectorLabels" . | nindent 4 }}



