name: nodemongo

on:
  push:
    paths:
    - 'src/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd ./src
        echo "${{ secrets.DOCKERPW }}" | docker login -u "ronald20065" --password-stdin
        docker image build -t ronald20065/nodemongo .
        docker push ronald20065/gitops:nodemongo
